// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUM_CjNwc54jFM5apQaNmQXBmkBbksQ6Q',
    appId: '1:162220779255:web:b1a7ae9833ac07cf5815f2',
    messagingSenderId: '162220779255',
    projectId: 'thi-gk-main',
    authDomain: 'thi-gk-main.firebaseapp.com',
    storageBucket: 'thi-gk-main.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Ja4jSMuj_-wKAzsq8Z6IUH0i9bJLW5c',
    appId: '1:162220779255:android:52d2f0ce2b6e7b3c5815f2',
    messagingSenderId: '162220779255',
    projectId: 'thi-gk-main',
    storageBucket: 'thi-gk-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWxP3uyfBhux_EuYlazPgLUN8_YcY5iE',
    appId: '1:162220779255:ios:efbefe6901cbe3815815f2',
    messagingSenderId: '162220779255',
    projectId: 'thi-gk-main',
    storageBucket: 'thi-gk-main.appspot.com',
    iosBundleId: 'com.example.groceryManagement',
  );

}